/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marl8n.messages.ui;

import com.marl8n.messages.ui.collections.FileData;

/**
 *
 * @author MIDP9
 */
public class MainUI extends javax.swing.JFrame {

    IFAddContact ifAddContact = null;
    IFTableOfContacts ifTableOfContacts = null;
    IFSearchContact ifSearchContact = null;
    IFDeleteContact ifDeleteContact = null;
    
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        FileData.Load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAddContact = new javax.swing.JMenuItem();
        miShowContacts = new javax.swing.JMenuItem();
        deleteContact = new javax.swing.JMenuItem();
        searchContact = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        jMenu1.setText("Options");

        miAddContact.setText("Add Contact");
        miAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddContactActionPerformed(evt);
            }
        });
        jMenu1.add(miAddContact);

        miShowContacts.setText("Show contacts");
        miShowContacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miShowContactsActionPerformed(evt);
            }
        });
        jMenu1.add(miShowContacts);

        deleteContact.setText("Delete Contact");
        deleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteContactActionPerformed(evt);
            }
        });
        jMenu1.add(deleteContact);

        searchContact.setText("Search Contact");
        searchContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchContactActionPerformed(evt);
            }
        });
        jMenu1.add(searchContact);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddContactActionPerformed
        if ( ifAddContact == null || ifAddContact.isClosed() ) {
            ifAddContact = new IFAddContact();
            dp.add(ifAddContact);
        }
        ifAddContact.show();
    }//GEN-LAST:event_miAddContactActionPerformed

    private void miShowContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miShowContactsActionPerformed
        if ( ifTableOfContacts == null || ifTableOfContacts.isClosed() ) {
            ifTableOfContacts = new IFTableOfContacts();
            dp.add(ifTableOfContacts);
        }
        ifTableOfContacts.show();
    }//GEN-LAST:event_miShowContactsActionPerformed

    private void searchContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchContactActionPerformed
        if ( ifSearchContact == null || ifSearchContact.isClosed() ) {
            ifSearchContact = new IFSearchContact();
            dp.add(ifSearchContact);
        }
        ifSearchContact.show();
    }//GEN-LAST:event_searchContactActionPerformed

    private void deleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteContactActionPerformed
        if ( ifDeleteContact == null || ifDeleteContact.isClosed() ) {
            ifDeleteContact = new IFDeleteContact();
            dp.add(ifDeleteContact);
        }
        ifDeleteContact.show();
    }//GEN-LAST:event_deleteContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem deleteContact;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miAddContact;
    private javax.swing.JMenuItem miShowContacts;
    private javax.swing.JMenuItem searchContact;
    // End of variables declaration//GEN-END:variables
}
